name: Test rerun

on: 
  workflow_dispatch:
    inputs:
      custom_date:
        required: false
        type: string

jobs:
  test_rerun:
    name: Test rerun
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: |
          echo ${{ github.event.inputs.custom_date }}
        env:
          RAILS_ENV: production
          RAILS_MASTER_KEY: '${{ secrets.RAILS_MASTER_KEY }}'
          DATABASE_URL: '${{ secrets.DATABASE_URL }}'
